#!/usr/bin/env bash
# peephole one-line installer (Debian/Ubuntu):
#   curl -fsSL https://raw.githubusercontent.com/overcuriousity/peephole/master/install.sh | sudo bash
#
# Non-interactive use (env overrides, no prompts):
#   curl -fsSL ... | sudo MAXMIND_ACCOUNT_ID=123456 MAXMIND_LICENSE_KEY=abc \
#       PEEPHOLE_DOMAIN=peephole.example.net bash
set -euo pipefail

REPO="overcuriousity/peephole"
ASSET="peephole-x86_64-unknown-linux-gnu"
BASE_URL="https://github.com/${REPO}/releases/download/latest"
INSTALL_BIN="/usr/local/bin/peephole"
CONFIG_DIR="/etc/peephole"
CONFIG_FILE="${CONFIG_DIR}/config.toml"
DATA_DIR="/var/lib/peephole"
UNIT_FILE="/etc/systemd/system/peephole.service"

info() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# --- preconditions -----------------------------------------------------------
[ "$(id -u)" -eq 0 ] || die "must run as root (use sudo)"
command -v apt-get >/dev/null 2>&1 || die "this installer supports Debian/Ubuntu (apt) systems only"

# Read from the terminal even when the script itself arrives via a pipe.
if [ -r /dev/tty ]; then
    INTERACTIVE=1
else
    INTERACTIVE=0
fi

prompt() {
    # prompt <varname> <message> [default]
    local var="$1" msg="$2" default="${3:-}" value
    if [ -n "${!var:-}" ]; then
        return 0  # preset via environment
    fi
    [ "$INTERACTIVE" -eq 1 ] || die "missing required setting: ${var} (set it as an environment variable for non-interactive installs)"
    if [ -n "$default" ]; then
        printf '%s [%s]: ' "$msg" "$default" > /dev/tty
    else
        printf '%s: ' "$msg" > /dev/tty
    fi
    read -r value < /dev/tty
    if [ -z "$value" ]; then
        value="$default"
    fi
    [ -n "$value" ] || die "no value provided for ${var}"
    printf -v "$var" '%s' "$value"
}

toml_safe() {
    if [[ "$1" == *[\"\\]* ]] || [[ "$1" == *$'\n'* ]]; then
        die "value contains characters that are not allowed (quote, backslash, newline): $1"
    fi
}

# --- prerequisites -----------------------------------------------------------
info "Installing prerequisites (nmap, curl, ca-certificates, sqlite3)"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq nmap curl ca-certificates sqlite3

# --- download + verify -------------------------------------------------------
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

info "Downloading latest peephole build"
curl -fsSL "${BASE_URL}/${ASSET}.tar.gz"        -o "${tmpdir}/${ASSET}.tar.gz"
curl -fsSL "${BASE_URL}/${ASSET}.tar.gz.sha256" -o "${tmpdir}/${ASSET}.tar.gz.sha256"

info "Verifying checksum"
( cd "$tmpdir" && sha256sum -c "${ASSET}.tar.gz.sha256" )

tar -xzf "${tmpdir}/${ASSET}.tar.gz" -C "$tmpdir"

# --- install files -----------------------------------------------------------
info "Installing binary to ${INSTALL_BIN}"
install -m 0755 "${tmpdir}/${ASSET}/peephole" "$INSTALL_BIN"

mkdir -p "$CONFIG_DIR" "$DATA_DIR"

info "Installing signature rules to ${CONFIG_DIR}/rules"
mkdir -p "${CONFIG_DIR}/rules"
for rule in "${tmpdir}/${ASSET}/rules/"*.toml; do
    dest="${CONFIG_DIR}/rules/$(basename "$rule")"
    if [ -e "$dest" ]; then
        warn "keeping existing rule file: $dest"
    else
        install -m 0644 "$rule" "$dest"
    fi
done

# --- configuration -----------------------------------------------------------
if [ -e "$CONFIG_FILE" ]; then
    warn "existing config found at ${CONFIG_FILE}; leaving it untouched"
else
    info "Configuring peephole"
    prompt MAXMIND_ACCOUNT_ID  "MaxMind GeoLite2 account ID (https://www.maxmind.com/en/accounts/current/license-key)"
    prompt MAXMIND_LICENSE_KEY "MaxMind GeoLite2 license key"
    prompt PEEPHOLE_DOMAIN     "Public domain of the admin dashboard (WebAuthn relying party)"
    prompt PEEPHOLE_TRUSTED_PROXIES "Trusted proxy CIDRs, comma-separated (X-Forwarded-For is trusted from these)" "10.0.0.0/8"

    toml_safe "$MAXMIND_ACCOUNT_ID"
    toml_safe "$MAXMIND_LICENSE_KEY"
    toml_safe "$PEEPHOLE_DOMAIN"

    # comma-separated CIDRs -> TOML array
    proxies_toml="$(printf '%s' "$PEEPHOLE_TRUSTED_PROXIES" | tr ',' '\n' | sed 's/^ *//; s/ *$//' | sed 's/.*/"&"/' | paste -sd',' -)"
    proxies_toml="[${proxies_toml}]"

    cat > "$CONFIG_FILE" <<EOF
# peephole configuration — generated by install.sh
# Full reference: https://github.com/${REPO}/blob/master/deploy/config.example.toml

# Trap listener: HAProxy routes fallback (nonexistent-route) traffic here directly.
trap_listen = "0.0.0.0:8080"
# Admin listener: nginx terminates TLS in front of this.
admin_listen = "127.0.0.1:8443"

# SQLite database (WAL mode) and data dir (MaxMind DBs, Tor exit list snapshot).
database_path = "${DATA_DIR}/peephole.db"
data_dir = "${DATA_DIR}"

# Directory with TOML signature rules (editable without recompile).
rules_dir = "${CONFIG_DIR}/rules"

# Proxies whose X-Forwarded-For header is trusted for the real client IP.
trusted_proxies = ${proxies_toml}

[webauthn]
rp_id = "${PEEPHOLE_DOMAIN}"
origin = "https://${PEEPHOLE_DOMAIN}"
rp_name = "peephole"

[maxmind]
account_id = "${MAXMIND_ACCOUNT_ID}"
license_key = "${MAXMIND_LICENSE_KEY}"

[scan]
max_workers = 2            # concurrent nmap subprocesses
timeout_secs = 900         # per-scan wall-clock timeout
rescan_cooldown_hours = 24 # per-IP rescan cooldown (one level upgrade allowed)
max_scans_per_hour = 30    # global rate cap; excess jobs stay queued
never_scan = ["192.168.0.0/16"] # CIDRs never counter-scanned (own infra, monitoring)
EOF
    chmod 0600 "$CONFIG_FILE"
    info "Wrote ${CONFIG_FILE} (mode 0600 — contains your MaxMind license key)"
fi

# --- systemd -----------------------------------------------------------------
info "Installing systemd service"
install -m 0644 "${tmpdir}/${ASSET}/deploy/peephole.service" "$UNIT_FILE"
systemctl daemon-reload
if systemctl is-enabled peephole >/dev/null 2>&1; then
    systemctl restart peephole
    info "Restarted peephole service"
else
    systemctl enable --now peephole
    info "Enabled and started peephole service"
fi

# --- done --------------------------------------------------------------------
cat <<EOF

peephole is installed and running.

  service status : systemctl status peephole
  logs           : journalctl -u peephole -f
  config         : ${CONFIG_FILE}

Next steps:
  1. Route fallback traffic from HAProxy to the trap listener (0.0.0.0:8080).
  2. Terminate TLS with nginx in front of the admin listener (127.0.0.1:8443).
  3. Enroll your first FIDO2 admin key — see the enrollment instructions in
     the service logs (journalctl -u peephole) or the README:
     https://github.com/${REPO}#readme
EOF
