#!/usr/bin/env bash
# Exercises install.sh against a locally served tarball: fresh install,
# no-op re-run, forced upgrades (an edited unit kept, the rules directory of
# an older install left alone, database backed up), a failed upgrade that
# rolls back, the wizard, and what is in front of the trap (nothing, nginx
# here, a proxy elsewhere) with the port check, the checks of the trusted
# proxies and the admin domain, the admin password, the nginx checks and the
# cluster section every node gets (name, required advertise address).
# Runs as root on a throwaway Debian/Ubuntu host (CI: an ubuntu-24.04 runner).
# PEEPHOLE_BIN is the release binary (default target/release/peephole).
set -euo pipefail
cd "$(dirname "$0")/.."
case "$(uname -m)" in aarch64|arm64) TARGET=aarch64-unknown-linux-gnu ;; *) TARGET=x86_64-unknown-linux-gnu ;; esac
ASSET="peephole-${TARGET}"
apt-get update -qq && apt-get install -y -qq curl ca-certificates python3 systemd nmap sqlite3 procps nginx-light libnginx-mod-stream openssl >/dev/null

echo "== deploy files: nginx example generated by install.sh, nginx -t, systemd-analyze verify"
bash tests/deploy-check.sh

# The tarball, built like CI builds it; its version is what the binary
# reports, so a re-run sees the same version and does nothing.
BIN="${PEEPHOLE_BIN:-target/release/peephole}"
V1="$("$BIN" --version | awk '{print $2}')"
rm -rf "/tmp/$ASSET" /tmp/srv
tools/package.sh "$BIN" "$TARGET" "$V1" 0123456789abcdef0123456789abcdef01234567 /tmp/srv >/dev/null
tar -xzf "/tmp/srv/$ASSET.tar.gz" -C /tmp   # staged copy that later steps change and repack
repack() { ( cd /tmp && tar -czf "srv/$ASSET.tar.gz" "$ASSET" && cd srv && sha256sum "$ASSET.tar.gz" > "$ASSET.tar.gz.sha256" ); }
( cd /tmp/srv && python3 -m http.server 8999 >/dev/null 2>&1 & )
for _ in $(seq 1 50); do curl -fs -o /dev/null http://127.0.0.1:8999/ && break; sleep 0.1; done

# systemd is not PID 1 in a container: stub systemctl so the script's
# service steps become no-ops we can observe. /tmp/fail-start makes the next
# restart fail like a new version that does not come up, after "migrating"
# the database to a newer schema.
mkdir -p /tmp/bin
cat > /tmp/bin/systemctl <<'STUB'
#!/bin/sh
echo "systemctl $*" >> /tmp/systemctl.log
case "$1" in
  is-enabled) [ -e /tmp/enabled ]; exit $? ;;
  enable) touch /tmp/enabled ;;
  restart)
    if [ -e /tmp/fail-start ]; then
      rm -f /tmp/fail-start
      sqlite3 /var/lib/peephole/peephole.db 'PRAGMA user_version = 999'
      exit 1
    fi ;;
esac
exit 0
STUB
chmod +x /tmp/bin/systemctl
export PATH="/tmp/bin:$PATH"
export PEEPHOLE_SKIP_APT=1 PEEPHOLE_SKIP_HEALTH=1 BASE_URL="http://127.0.0.1:8999"
export MAXMIND_ACCOUNT_ID=1 MAXMIND_LICENSE_KEY=k PEEPHOLE_DOMAIN=peephole.test PEEPHOLE_TRUSTED_PROXIES=10.0.0.0/8
# Every node publishes a cluster address; the wizard runs unset it and answer.
export PEEPHOLE_CLUSTER_ADVERTISE=node.test:7443
NODE_NAME="$(hostname -s 2>/dev/null || hostname 2>/dev/null || uname -n)"
# The cluster listener's default address: both families where IPv6 is on.
if [ -e /proc/net/if_inet6 ]; then LISTEN_ANY='[::]'; else LISTEN_ANY=0.0.0.0; fi
# CI runs in a cloud: its metadata service would add a question to the wizard.
export PEEPHOLE_METADATA=0

echo "== token extraction survives journalctl prefixes"
tok="$(printf 'Sep 30 10:00:00 host peephole[123]: Open /enroll on the admin interface and enter this one-time token:\nSep 30 10:00:00 host peephole[123]: \nSep 30 10:00:00 host peephole[123]:   3f2a1c4e-1111-4222-8333-444455556666\n' | bash install.sh --extract-token)"
[ "$tok" = "3f2a1c4e-1111-4222-8333-444455556666" ] || { echo "token extraction broken: '$tok'"; exit 1; }

echo "== the admin domain and trusted proxy entries are checked like the wizard checks them"
[ "$(bash install.sh --check-domain 'https://Peephole.Example.net/admin/')" = peephole.example.net ]
[ "$(bash install.sh --check-domain 'peephole.example.net.')" = peephole.example.net ]
label63="$(printf '%063d' 0 | tr 0 a)"
[ "$(bash install.sh --check-domain "${label63}.example.net")" = "${label63}.example.net" ]
# An IP address cannot be a passkey's rp_id; a label has at most 63 characters.
for d in 'not a domain' localhost 'bad"domain' 10.0.0.5 "${label63}a.example.net"; do
    if bash install.sh --check-domain "$d" 2>/dev/null; then echo "domain '$d' accepted"; exit 1; fi
done

echo "== the nginx check of the admin domain's DNS: one of this machine's addresses, or the reason"
[ "$(bash install.sh --check-dns peephole.example.net '203.0.113.7 2001:db8::7' '10.0.0.2 203.0.113.7')" = ok ]
bash install.sh --check-dns peephole.example.net '2001:db8::7' '10.0.0.2,2001:db8::7' >/dev/null
if bash install.sh --check-dns peephole.test '' '10.0.0.2' 2>/tmp/dns.err; then echo "unresolved domain passed"; exit 1; fi
grep -q 'peephole.test does not resolve' /tmp/dns.err
if bash install.sh --check-dns peephole.example.net '198.51.100.1' '10.0.0.2 203.0.113.7' 2>/tmp/dns.err; then
    echo "domain pointing elsewhere passed"; exit 1
fi
grep -q 'points to 198.51.100.1 - not to this machine' /tmp/dns.err
for c in 10.0.0.5 10.0.0.0/24 2001:db8::/64; do
    bash install.sh --check-cidr "$c" >/dev/null || { echo "CIDR '$c' refused"; exit 1; }
done
for c in 10.0.0.0/33 2001:db8::/129 10.0.0.0/x example; do
    if bash install.sh --check-cidr "$c" 2>/dev/null; then echo "CIDR '$c' accepted"; exit 1; fi
done

echo "== the cluster advertise address is host:port with a port 1-65535"
for a in node.example:7443 '[2001:db8::1]:7443' 203.0.113.5:7443; do
    [ "$(bash install.sh --check-advertise "$a")" = ok ] || { echo "advertise '$a' refused"; exit 1; }
done
for a in bogus host:0 host:70000 host: :7443 '2001:db8::1:7443' 'two words:7443' 'a/b:80' '[::]:80' '[:]:80'; do
    if bash install.sh --check-advertise "$a" 2>/dev/null; then echo "advertise '$a' accepted"; exit 1; fi
done

echo "== refuses to install when systemd is not PID 1 (unless overridden)"
# Only checkable where systemd is not PID 1 (a container); on a real runner it is.
if [ "$(cat /proc/1/comm)" != systemd ]; then
    if PEEPHOLE_ALLOW_NO_SYSTEMD='' bash install.sh >/tmp/nopid1.log 2>&1; then echo "expected failure"; exit 1; fi
    grep -q "PID 1" /tmp/nopid1.log
    export PEEPHOLE_ALLOW_NO_SYSTEMD=1
fi

echo "== a version that is not a release tag is refused"
if PEEPHOLE_VERSION=../evil bash install.sh >/tmp/badver.log 2>&1; then echo "expected failure"; exit 1; fi
grep -q "release tag" /tmp/badver.log

echo "== PEEPHOLE_VERIFY=1 without a verifiable attestation is refused before anything is installed"
# The local test release has no attestation; without gh it cannot be checked at all.
if command -v gh >/dev/null 2>&1; then expect="did not verify"; else expect="needs the GitHub CLI"; fi
if PEEPHOLE_VERIFY=1 bash install.sh >/tmp/verify.log 2>&1; then echo "expected failure"; exit 1; fi
grep -q "$expect" /tmp/verify.log
test ! -e /usr/local/bin/peephole

# The nginx steps in the closing summary appear in this order (certificate
# while the distribution's default site still serves, then the default site
# out of the way of the catch-all, then the site in, then a reload).
step_line() { grep -nF -- "$1" "$2" | head -1 | cut -d: -f1; }
steps_in_order() {
    local log="$1" prev=0 n; shift
    for s in "$@"; do
        n="$(step_line "$s" "$log")"
        if [ -z "$n" ] || [ "$n" -le "$prev" ]; then
            echo "nginx step '$s' missing or out of order"; cat "$log"; exit 1
        fi
        prev="$n"
    done
}

echo "== fresh install"
# A preset PEEPHOLE_TRUSTED_PROXIES no longer means remote: PEEPHOLE_FRONT says so.
PEEPHOLE_FRONT=remote bash install.sh > /tmp/fresh.log 2>&1 || { cat /tmp/fresh.log; exit 1; }
test -x /usr/local/bin/peephole
test -f /etc/peephole/config.toml
# The signature rules are built into the binary: none on disk, none shipped.
test ! -e /etc/peephole/rules
test ! -e "/tmp/$ASSET/rules"
test ! -e /var/lib/peephole/.installed-rules.sha256
if grep -q rules_dir /etc/peephole/config.toml; then echo "generated config sets rules_dir"; exit 1; fi
grep -q 'rules built in' /tmp/fresh.log
test -f /etc/peephole/nginx.example.conf
test -f /var/lib/peephole/.installed-unit.sha256
test -f /etc/peephole/config.example.toml
[ "$(stat -c %a /etc/peephole)" = 750 ] && [ "$(stat -c %a /var/lib/peephole)" = 700 ]
[ "$(stat -c %a /etc/peephole/config.toml)" = 600 ]
grep -q '^never_scan = \[\]' /etc/peephole/config.toml
# The scanner is opt-in: off without a terminal.
grep -q '^scanner = false' /etc/peephole/config.toml
# Top level (before the first table), keep everything by default.
[ "$(grep -m1 -n -E '^(retention_days = 0|\[)' /etc/peephole/config.toml)" = "$(grep -n '^retention_days = 0' /etc/peephole/config.toml)" ]
grep -q 'commit 0123456789ab' /tmp/fresh.log
grep -q 'peephole.test' /etc/peephole/config.toml
grep -q 'server_name peephole.test;' /etc/peephole/nginx.example.conf
grep -q 'default_server' /etc/peephole/nginx.example.conf
grep -q 'systemctl enable --now peephole' /tmp/systemctl.log
steps_in_order /tmp/fresh.log 'certbot certonly --nginx -d peephole.test' 'rm /etc/nginx/sites-enabled/default' \
    'cp /etc/peephole/nginx.example.conf' 'ln -s ../sites-available/peephole' 'nginx -t && systemctl reload nginx'
grep -q 'listen 443 ssl http2;' /etc/peephole/nginx.example.conf
if grep -q '^ *http2 on' /etc/peephole/nginx.example.conf; then echo "http2 on needs nginx >= 1.25.1"; exit 1; fi
grep -q 'sites-enabled/default' /etc/peephole/nginx.example.conf
# No proxy on this machine: the trap's TLS listener faces the remote proxy,
# and nginx here keeps 443 for the admin site (no stream config).
grep -Eq '^trap_tls_listen = "(0\.0\.0\.0|\[::\]):8081"' /etc/peephole/config.toml
test ! -e /etc/peephole/nginx-stream.example.conf
grep -q 'ssl_reject_handshake on' /etc/peephole/nginx.example.conf
# Every node has a cluster section: named after the machine, the listener on the advertised port.
grep -q '^\[cluster\]' /etc/peephole/config.toml
grep -q "^node_name = \"${NODE_NAME}\"" /etc/peephole/config.toml
grep -qxF "listen = \"${LISTEN_ANY}:7443\"" /etc/peephole/config.toml
grep -q '^advertise = "node.test:7443"' /etc/peephole/config.toml

echo "== re-run is a no-op"
out="$(bash install.sh)"
echo "$out" | grep -q "already up to date"

echo "== forced upgrade over an install that read its rules from disk: the rules directory and rules_dir stay, the operator is told once; an unedited unit is replaced"
# What an older installer left: rules (one edited), their manifest, rules_dir.
mkdir -p /etc/peephole/rules
echo '# operator edit' > /etc/peephole/rules/sqli.toml
echo "0000 sqli.toml" > /var/lib/peephole/.installed-rules.sha256
sed -i '1a rules_dir = "/etc/peephole/rules"' /etc/peephole/config.toml
printf 'test2 2026-01-02T00:00:00Z 1111111111111111111111111111111111111111\n' > "/tmp/$ASSET/VERSION"
echo '# upstream unit change' >> "/tmp/$ASSET/deploy/peephole.service"
repack
echo '# operator note' >> /etc/peephole/nginx.example.conf
# A database to back up (the daemon never ran here).
sqlite3 /var/lib/peephole/peephole.db 'CREATE TABLE t (x); PRAGMA user_version = 5'
chmod 0644 /var/lib/peephole/peephole.db
PEEPHOLE_FORCE=1 bash install.sh > /tmp/upgrade.log 2>&1 || { cat /tmp/upgrade.log; exit 1; }
grep -q '# operator note' /etc/peephole/nginx.example.conf
grep -q '# operator edit' /etc/peephole/rules/sqli.toml
grep -q '/etc/peephole/rules is no longer used' /tmp/upgrade.log
grep -q 'rules_dir in /etc/peephole/config.toml is ignored' /tmp/upgrade.log
grep -q '^rules_dir = ' /etc/peephole/config.toml
test ! -e /var/lib/peephole/.installed-rules.sha256
/usr/local/bin/peephole check-config /etc/peephole/config.toml | grep -q 'rules_dir.*is ignored'
grep -q '# upstream unit change' /etc/systemd/system/peephole.service
test ! -e /etc/systemd/system/peephole.service.new
grep -q 'systemctl restart peephole' /tmp/systemctl.log
test -x /usr/local/bin/peephole.prev
[ "$(stat -c %a /var/lib/peephole/peephole.db)" = 600 ]
backup="$(ls /var/lib/peephole/backup-*.db)"
[ "$(sqlite3 "$backup" 'PRAGMA user_version')" = 5 ]
[ "$(stat -c %a "$backup")" = 600 ]

echo "== an edited unit is kept and the new one placed beside it; two database backups are kept"
echo '# operator unit edit' >> /etc/systemd/system/peephole.service
echo '# upstream unit change 2' >> "/tmp/$ASSET/deploy/peephole.service"
repack
for _ in 1 2; do sleep 1.1; PEEPHOLE_FORCE=1 bash install.sh > /tmp/unit.log 2>&1 || { cat /tmp/unit.log; exit 1; }; done
grep -q '# operator unit edit' /etc/systemd/system/peephole.service
grep -q '# upstream unit change 2' /etc/systemd/system/peephole.service.new
grep -q 'systemctl edit peephole' /tmp/unit.log
# Told once: not again on later upgrades.
if grep -q 'no longer used' /tmp/unit.log; then echo "rules notice repeated"; exit 1; fi
test -d /etc/peephole/rules
[ "$(find /var/lib/peephole -name 'backup-*.db' | wc -l)" = 2 ]

echo "== a new version that does not start is rolled back: binary and unit; a cluster node keeps its database"
rm -f /etc/systemd/system/peephole.service.new
cp -p /etc/systemd/system/peephole.service /tmp/unit.before
echo '# broken release' >> "/tmp/$ASSET/deploy/peephole.service"
repack
touch /tmp/fail-start
if PEEPHOLE_FORCE=1 bash install.sh > /tmp/rollback.log 2>&1; then echo "expected failure"; cat /tmp/rollback.log; exit 1; fi
grep -q 'rolled back' /tmp/rollback.log
grep -q 'running again' /tmp/rollback.log
grep -q 'keeping it, since restoring would rewind' /tmp/rollback.log
if grep -q 'restoring /var/lib/peephole/backup-' /tmp/rollback.log; then echo "cluster node's database restored"; exit 1; fi
cmp /tmp/unit.before /etc/systemd/system/peephole.service
test ! -e /etc/systemd/system/peephole.service.new
test ! -e /usr/local/bin/peephole.prev
[ "$(sqlite3 /var/lib/peephole/peephole.db 'PRAGMA user_version')" = 999 ]
kept="$(sed -n 's/.*the backup stays in \(\/var\/lib\/peephole\/backup-[^)]*\.db\)).*/\1/p' /tmp/rollback.log)"
[ "$(sqlite3 "$kept" 'PRAGMA user_version')" = 5 ]
/usr/local/bin/peephole --version

echo "== a node without a [cluster] section gets its database back"
cp -p /etc/peephole/config.toml /tmp/config.cluster
sed -i '/^\[cluster\]/,$d' /etc/peephole/config.toml
sqlite3 /var/lib/peephole/peephole.db 'PRAGMA user_version = 5'
touch /tmp/fail-start
if PEEPHOLE_FORCE=1 bash install.sh > /tmp/rollback.log 2>&1; then echo "expected failure"; cat /tmp/rollback.log; exit 1; fi
grep -q 'running again' /tmp/rollback.log
grep -q 'restoring /var/lib/peephole/backup-' /tmp/rollback.log
[ "$(sqlite3 /var/lib/peephole/peephole.db 'PRAGMA user_version')" = 5 ]
cp -p /tmp/config.cluster /etc/peephole/config.toml

echo "== forced re-run with wizard variables set leaves config and nginx example alone"
md5sum /etc/peephole/config.toml /etc/peephole/nginx.example.conf > /tmp/before.md5
PEEPHOLE_FORCE=1 PEEPHOLE_ROLES=scanner PEEPHOLE_LOCAL_PROXY=1 PEEPHOLE_CLUSTER=1 \
    PEEPHOLE_CLUSTER_NAME=other PEEPHOLE_CLUSTER_LISTEN=0.0.0.0:7443 \
    bash install.sh > /tmp/forced-vars.log 2>&1 || { cat /tmp/forced-vars.log; exit 1; }
md5sum -c --quiet /tmp/before.md5

echo "== fresh headless scanner in distributed mode: no domain, no MaxMind"
rm -rf /etc/peephole /var/lib/peephole /usr/local/bin/peephole /usr/local/bin/peephole.prev /tmp/enabled
env -u MAXMIND_ACCOUNT_ID -u MAXMIND_LICENSE_KEY -u PEEPHOLE_DOMAIN \
    PEEPHOLE_ROLES=scanner PEEPHOLE_CLUSTER_NAME=scanner-1 PEEPHOLE_CLUSTER_LISTEN=0.0.0.0:7443 \
    bash install.sh > /tmp/headless.log 2>&1 || { cat /tmp/headless.log; exit 1; }
grep -q '^\[cluster\]' /etc/peephole/config.toml
grep -q '^listener = false' /etc/peephole/config.toml
grep -q '^web = false' /etc/peephole/config.toml
if grep -q 'webauthn\|maxmind\|trap_listen\|admin_listen' /etc/peephole/config.toml; then
    echo "headless config has role-specific settings"; exit 1
fi
grep -q 'ed25519:' /tmp/headless.log
test ! -e /etc/peephole/nginx.example.conf
/usr/local/bin/peephole check-config /etc/peephole/config.toml
# The node lists itself once the daemon has run (`cluster members` is read-only
# and systemd is stubbed here); the config names it.
grep -q '^node_name = "scanner-1"' /etc/peephole/config.toml
reset_install() {
    rm -rf /etc/peephole /var/lib/peephole /usr/local/bin/peephole /usr/local/bin/peephole.prev /tmp/enabled
}

echo "== wizard: trap only, behind a local nginx (answers typed at the prompts)"
reset_install
# trap? yes · scanner? no · web? no · in front: local · own addresses: none ·
# nginx? no · node name: the hostname · advertise · token: none · MaxMind: skip ·
# AbuseIPDB key · Shodan: skip · InternetDB? no
printf 'y\nn\nn\nlocal\n\nn\n\ntrap1.example:7443\n\n\nabuse-key-1\n\nn\n' > /tmp/answers
# PEEPHOLE_TRUSTED_PROXIES stays preset (10.0.0.0/8): the local proxy answer replaces it, with a warning.
env -u MAXMIND_ACCOUNT_ID -u MAXMIND_LICENSE_KEY -u PEEPHOLE_DOMAIN -u PEEPHOLE_CLUSTER_ADVERTISE \
    PEEPHOLE_TTY=/tmp/answers bash install.sh > /tmp/wizard1.log 2>&1 || { cat /tmp/wizard1.log; exit 1; }
grep -q 'PEEPHOLE_TRUSTED_PROXIES.*ignored' /tmp/wizard1.log
# The nginx checks pass here (no domain to resolve): the default would be yes.
grep -q 'no other site listens on port 443' /tmp/wizard1.log
grep -q 'Set up nginx now? \[Y/n\]' /tmp/wizard1.log
grep -q '^listener = true' /etc/peephole/config.toml
grep -q '^scanner = false' /etc/peephole/config.toml
grep -q '^web = false' /etc/peephole/config.toml
grep -q '^trap_listen = "127.0.0.1:8080"' /etc/peephole/config.toml
grep -q '^trusted_proxies = \["127.0.0.1/32","::1/128"\]' /etc/peephole/config.toml
if grep -q 'webauthn\|maxmind\|admin_listen' /etc/peephole/config.toml; then
    echo "trap-only config has other roles' settings"; cat /etc/peephole/config.toml; exit 1
fi
# No cluster question, but a cluster section: the hostname, the typed address,
# the listener on its port; the token question names the later command.
grep -q "^node_name = \"${NODE_NAME}\"" /etc/peephole/config.toml
grep -q '^advertise = "trap1.example:7443"' /etc/peephole/config.toml
grep -qxF "listen = \"${LISTEN_ANY}:7443\"" /etc/peephole/config.toml
grep -q 'peephole cluster join' /tmp/wizard1.log
if grep -q 'Take part in a cluster' /tmp/wizard1.log; then echo "the cluster question is still asked"; exit 1; fi
grep -q '^api_key = "abuse-key-1"' /etc/peephole/config.toml
if grep -q '\[shodan\]\|\[internetdb\]' /etc/peephole/config.toml; then
    echo "skipped enrichment APIs were configured"; cat /etc/peephole/config.toml; exit 1
fi
/usr/local/bin/peephole check-config /etc/peephole/config.toml
grep -q 'trap listener (127.0.0.1:8080)' /tmp/wizard1.log
grep -q '^trap_tls_listen = "127.0.0.1:8081"' /etc/peephole/config.toml
steps_in_order /tmp/wizard1.log 'rm /etc/nginx/sites-enabled/default' 'cp /etc/peephole/nginx.example.conf' \
    'cp /etc/peephole/nginx-stream.example.conf /etc/nginx/peephole-stream.conf' \
    "echo 'include /etc/nginx/peephole-stream.conf;' >> /etc/nginx/nginx.conf" 'nginx -t && systemctl reload nginx'
# Port 443 untouched to the trap's TLS listener, with a PROXY header.
grep -q 'proxy_pass 127.0.0.1:8081;' /etc/peephole/nginx-stream.example.conf
grep -q 'proxy_protocol on;' /etc/peephole/nginx-stream.example.conf
if grep -q 'ssl_preread on' /etc/peephole/nginx-stream.example.conf; then
    echo "trap-only stream config routes by name although there is no admin site"; exit 1
fi
if grep -q 'certbot\|certificate' /tmp/wizard1.log; then echo "trap-only node told to get a certificate"; exit 1; fi
grep -q 'default_server' /etc/peephole/nginx.example.conf
grep -q 'proxy_pass http://127.0.0.1:8080' /etc/peephole/nginx.example.conf
# shellcheck disable=SC2016  # the dollar sign is literal nginx syntax
grep -qF 'X-Forwarded-For $remote_addr' /etc/peephole/nginx.example.conf
if grep -q 'server_name peephole\|8443\|proxy_add_x_forwarded_for' /etc/peephole/nginx.example.conf; then
    echo "trap-only nginx example has an admin block or a spoofable header"; exit 1
fi

echo "== wizard: no role at all is refused before anything is written"
reset_install
printf 'n\nn\nn\n' > /tmp/answers
if env -u MAXMIND_ACCOUNT_ID -u MAXMIND_LICENSE_KEY -u PEEPHOLE_DOMAIN \
    PEEPHOLE_TTY=/tmp/answers bash install.sh > /tmp/wizard2.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q "at least one" /tmp/wizard2.log
test ! -e /etc/peephole/config.toml
test ! -e /usr/local/bin/peephole

echo "== wizard: a quote in an answer is refused"
reset_install
# trap? no · scanner? no · web? yes · domain with a quote
printf 'n\nn\ny\nbad"domain\n' > /tmp/answers
if env -u MAXMIND_ACCOUNT_ID -u MAXMIND_LICENSE_KEY -u PEEPHOLE_DOMAIN \
    PEEPHOLE_TTY=/tmp/answers bash install.sh > /tmp/wizard3.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q "not allowed" /tmp/wizard3.log
test ! -e /etc/peephole/config.toml
test ! -e /usr/local/bin/peephole

echo "== preset roles with no role in them are refused before anything is written"
reset_install
if PEEPHOLE_ROLES=, bash install.sh > /tmp/noroles.log 2>&1; then echo "expected failure"; exit 1; fi
grep -q "at least one" /tmp/noroles.log
test ! -e /usr/local/bin/peephole

echo "== wizard: an advertise address without a port is asked again; a listener the binary rejects leaves no config behind"
reset_install
# trap? no · scanner? yes · web? no · own addresses: none · name · advertise "bogus"
# (asked again) · advertise · token (none) · MaxMind: skip; the listener "bogus" is preset
printf 'n\ny\nn\n\nscanner-9\nbogus\nscan9.example:7443\n\n\n' > /tmp/answers
if env -u MAXMIND_ACCOUNT_ID -u MAXMIND_LICENSE_KEY -u PEEPHOLE_DOMAIN -u PEEPHOLE_CLUSTER_ADVERTISE \
    PEEPHOLE_CLUSTER_LISTEN=bogus PEEPHOLE_TTY=/tmp/answers bash install.sh > /tmp/wizard-bad.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q "'bogus' is not host:port with a port 1-65535" /tmp/wizard-bad.log
grep -q "failed validation" /tmp/wizard-bad.log
test ! -e /etc/peephole/config.toml

echo "== wizard: re-run after the rejected answer asks again (scanner in a cluster)"
# No reset: the binary from the failed run is in place.
# trap? no · scanner? yes · web? no · own addresses: none · name · advertise ·
# token (none) · MaxMind: skip
printf 'n\ny\nn\n\nscanner-9\nscan9.example:7443\n\n\n' > /tmp/answers
env -u MAXMIND_ACCOUNT_ID -u MAXMIND_LICENSE_KEY -u PEEPHOLE_DOMAIN -u PEEPHOLE_CLUSTER_ADVERTISE \
    PEEPHOLE_TTY=/tmp/answers bash install.sh > /tmp/wizard4.log 2>&1 || { cat /tmp/wizard4.log; exit 1; }
if grep -q 'already up to date' /tmp/wizard4.log; then echo "re-run after a failed first install skipped the wizard"; exit 1; fi
grep -q '^node_name = "scanner-9"' /etc/peephole/config.toml
grep -qxF "listen = \"${LISTEN_ANY}:7443\"" /etc/peephole/config.toml
grep -q '^advertise = "scan9.example:7443"' /etc/peephole/config.toml
# The InternetDB question was not answered: its default (yes) applies.
grep -q '^\[internetdb\]' /etc/peephole/config.toml
grep -q 'ed25519:' /tmp/wizard4.log

# certbot stand-in: records its arguments and writes a self-signed
# certificate where Let's Encrypt would; /tmp/certbot-fail makes it fail.
cat > /tmp/bin/certbot <<'STUB'
#!/bin/sh
echo "certbot $*" >> /tmp/certbot.log
[ -e /tmp/certbot-fail ] && exit 1
d=""
while [ $# -gt 0 ]; do [ "$1" = -d ] && d="$2"; shift; done
mkdir -p "/etc/letsencrypt/live/$d"
openssl req -x509 -newkey rsa:2048 -nodes -days 1 -subj "/CN=$d" \
    -keyout "/etc/letsencrypt/live/$d/privkey.pem" -out "/etc/letsencrypt/live/$d/fullchain.pem" >/dev/null 2>&1
STUB
chmod +x /tmp/bin/certbot
reset_nginx() {
    rm -rf /etc/nginx/sites-available/peephole /etc/nginx/sites-enabled/peephole /etc/letsencrypt /tmp/certbot.log /tmp/certbot-fail \
        /etc/nginx/peephole-stream.conf
    sed -i '\|^# peephole: port 443 by server name|d; \|^include /etc/nginx/peephole-stream.conf;|d' /etc/nginx/nginx.conf
    [ -e /etc/nginx/sites-enabled/default ] || ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
}

echo "== PEEPHOLE_NGINX=1: certificate, default site out, site in, nginx -t, reload"
reset_install; reset_nginx
PEEPHOLE_NGINX=1 PEEPHOLE_LOCAL_PROXY=1 bash install.sh > /tmp/nginx-auto.log 2>&1 || { cat /tmp/nginx-auto.log; exit 1; }
grep -q -- '-d peephole.test' /tmp/certbot.log
grep -q -- '--register-unsafely-without-email' /tmp/certbot.log
grep -q -- '--deploy-hook systemctl reload nginx' /tmp/certbot.log
test -f /etc/nginx/sites-available/peephole
[ "$(readlink /etc/nginx/sites-enabled/peephole)" = ../sites-available/peephole ]
test ! -e /etc/nginx/sites-enabled/default
grep -q 'server_name peephole.test;' /etc/nginx/sites-available/peephole
# Port 443 by server name: the stream config is in, included once, and the
# admin site moved behind it.
grep -q 'ssl_preread on;' /etc/nginx/peephole-stream.conf
[ "$(grep -c '^include /etc/nginx/peephole-stream.conf;' /etc/nginx/nginx.conf)" = 1 ]
grep -q 'listen 127.0.0.1:8444 ssl http2 proxy_protocol;' /etc/nginx/sites-available/peephole
if [ ! -e /proc/net/if_inet6 ] && grep -q 'listen \[::\]' /etc/nginx/sites-available/peephole /etc/nginx/peephole-stream.conf; then
    echo "IPv6 listeners kept on a machine without IPv6"; exit 1
fi
nginx -t -q
grep -q 'systemctl reload nginx' /tmp/systemctl.log
grep -q 'nginx is configured' /tmp/nginx-auto.log
if grep -q 'certbot certonly\|rm /etc/nginx/sites-enabled/default\|Terminate TLS' /tmp/nginx-auto.log; then
    echo "manual nginx steps printed although nginx was configured"; cat /tmp/nginx-auto.log; exit 1
fi

echo "== PEEPHOLE_NGINX=1 with another HTTPS site on this nginx: port 443 is not taken over"
reset_install; reset_nginx
cat > /etc/nginx/sites-available/shop <<'SITE'
server {
    listen 443 ssl;
    server_name shop.test;
    ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
    ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
}
SITE
ln -s ../sites-available/shop /etc/nginx/sites-enabled/shop
PEEPHOLE_NGINX=1 PEEPHOLE_LOCAL_PROXY=1 bash install.sh > /tmp/nginx-other.log 2>&1 || { cat /tmp/nginx-other.log; exit 1; }
grep -q 'shop.*443\|443.*shop' /tmp/nginx-other.log || { cat /tmp/nginx-other.log; exit 1; }
test ! -e /etc/nginx/sites-available/peephole
test ! -e /etc/nginx/peephole-stream.conf
if grep -q 'peephole-stream' /etc/nginx/nginx.conf; then echo "include added although 443 is taken"; exit 1; fi
grep -q 'cp /etc/peephole/nginx-stream.example.conf' /tmp/nginx-other.log
rm -f /etc/nginx/sites-enabled/shop /etc/nginx/sites-available/shop

echo "== PEEPHOLE_NGINX=1, certificate refused: nginx left as it was, manual steps printed"
reset_install; reset_nginx
touch /tmp/certbot-fail
PEEPHOLE_NGINX=1 PEEPHOLE_LOCAL_PROXY=1 \
    bash install.sh > /tmp/nginx-fail.log 2>&1 || { cat /tmp/nginx-fail.log; exit 1; }
grep -q -- '--register-unsafely-without-email' /tmp/certbot.log
# A preset PEEPHOLE_NGINX=1 tries despite the failing DNS check.
grep -q 'peephole.test does not resolve' /tmp/nginx-fail.log
grep -q 'no certificate for peephole.test' /tmp/nginx-fail.log
test ! -e /etc/nginx/sites-available/peephole
test ! -e /etc/nginx/peephole-stream.conf
if grep -q 'peephole-stream' /etc/nginx/nginx.conf; then echo "include left behind"; exit 1; fi
test -L /etc/nginx/sites-enabled/default
steps_in_order /tmp/nginx-fail.log 'certbot certonly --nginx -d peephole.test' 'rm /etc/nginx/sites-enabled/default' \
    'cp /etc/peephole/nginx.example.conf' 'nginx -t && systemctl reload nginx'

echo "== PEEPHOLE_NGINX=1 for a trap that trusts a remote proxy is refused before anything is written"
reset_install; reset_nginx
if PEEPHOLE_NGINX=1 PEEPHOLE_LOCAL_PROXY=0 PEEPHOLE_ROLES=listener bash install.sh > /tmp/nginx-refused.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q 'PEEPHOLE_NGINX=1 needs' /tmp/nginx-refused.log
test ! -e /usr/local/bin/peephole
reset_nginx

echo "== wizard nginx: an unresolvable domain makes the default no"
reset_install; reset_nginx
# Web only, the domain preset (peephole.test does not resolve); every answer at its default.
: > /tmp/answers
env -u PEEPHOLE_CLUSTER_ADVERTISE PEEPHOLE_ROLES=web PEEPHOLE_TTY=/tmp/answers bash install.sh > /tmp/wizard-nginx.log 2>&1 \
    || { cat /tmp/wizard-nginx.log; exit 1; }
# The domain points here (no proxy elsewhere): the advertise default.
grep -q 'Address other nodes dial (host:port) \[peephole.test:7443\]' /tmp/wizard-nginx.log
grep -q '^advertise = "peephole.test:7443"' /etc/peephole/config.toml
grep -q 'does not resolve\|points to' /tmp/wizard-nginx.log
grep -q 'Port 80 must be reachable' /tmp/wizard-nginx.log
grep -q 'Set up nginx now? \[y/N\]' /tmp/wizard-nginx.log
test ! -e /etc/nginx/sites-available/peephole
test ! -e /tmp/certbot.log
grep -q 'certbot certonly --nginx -d peephole.test' /tmp/wizard-nginx.log
# The password question was answered no: passkeys only.
grep -q 'Also allow signing in with a password? \[y/N\]' /tmp/wizard-nginx.log
if grep -q 'with your password' /tmp/wizard-nginx.log; then echo "password sign-in offered though none was set"; exit 1; fi
reset_nginx

echo "== wizard password: too short and a mismatch are asked again; the hash is stored"
reset_install; reset_nginx
# Web only, the domain preset · password? yes · too short (twice) · two that differ ·
# the password twice · nginx? no · node name: the hostname · advertise · the rest at its defaults
# shellcheck disable=SC2016  # quote, backslash, dollar sign and spaces, literally
wpw='wiz "pass\ $1 ok'
printf '%s\n' y short short 'longenough-pass-1' 'longenough-pass-2' "$wpw" "$wpw" n '' web.example:7444 > /tmp/answers
env -u PEEPHOLE_CLUSTER_ADVERTISE PEEPHOLE_ROLES=web PEEPHOLE_TTY=/tmp/answers bash install.sh > /tmp/wizard-password.log 2>&1 \
    || { cat /tmp/wizard-password.log; exit 1; }
grep -q '^advertise = "web.example:7444"' /etc/peephole/config.toml
grep -qxF "listen = \"${LISTEN_ANY}:7444\"" /etc/peephole/config.toml
grep -q 'Too short.' /tmp/wizard-password.log
grep -q 'They differ.' /tmp/wizard-password.log
if grep -q 'wiz "pass\|longenough' /etc/peephole/config.toml /tmp/wizard-password.log; then
    echo "the password was written out"; exit 1
fi
# shellcheck disable=SC2016  # the dollar signs are literal
sqlite3 /var/lib/peephole/peephole.db "SELECT value FROM intel_meta WHERE key='admin_password_hash'" | grep -q '^\$argon2id\$'
[ "$(sqlite3 /var/lib/peephole/peephole.db "SELECT value FROM intel_meta WHERE key='admin_login_method'")" = both ]
test ! -e /etc/nginx/sites-available/peephole

echo "== unattended password without the web role: ignored, with a warning"
reset_install
PEEPHOLE_FRONT=remote PEEPHOLE_ROLES=listener PEEPHOLE_ADMIN_PASSWORD='long enough password' \
    bash install.sh > /tmp/password-noweb.log 2>&1 || { cat /tmp/password-noweb.log; exit 1; }
grep -q 'PEEPHOLE_ADMIN_PASSWORD is ignored: this node has no web interface' /tmp/password-noweb.log

echo "== unattended password: hashed, never in the config"
reset_install
# shellcheck disable=SC2016  # quote, backslash, dollar sign and spaces, literally
pw='pa"ss \ $word 12'
PEEPHOLE_FRONT=remote PEEPHOLE_ADMIN_PASSWORD="$pw" bash install.sh > /tmp/password.log 2>&1 \
    || { cat /tmp/password.log; exit 1; }
if grep -q 'pa"ss' /etc/peephole/config.toml /tmp/password.log; then echo "the password was written out"; exit 1; fi
# shellcheck disable=SC2016  # the dollar signs are literal
sqlite3 /var/lib/peephole/peephole.db "SELECT value FROM intel_meta WHERE key='admin_password_hash'" | grep -q '^\$argon2id\$'
[ "$(sqlite3 /var/lib/peephole/peephole.db "SELECT value FROM intel_meta WHERE key='admin_login_method'")" = both ]
grep -q 'Sign-in: both' /tmp/password.log
grep -q 'sign in at https://peephole.test/login with your password' /tmp/password.log

echo "== unattended password: a short one is refused before anything is written"
reset_install
if PEEPHOLE_FRONT=remote PEEPHOLE_ADMIN_PASSWORD=short bash install.sh > /tmp/password-short.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q 'PEEPHOLE_ADMIN_PASSWORD: at least 12 characters' /tmp/password-short.log
test ! -e /etc/peephole/config.toml
test ! -e /usr/local/bin/peephole

echo "== unattended: a bad join token does not fail the install"
reset_install
env -u MAXMIND_ACCOUNT_ID -u MAXMIND_LICENSE_KEY -u PEEPHOLE_DOMAIN \
    PEEPHOLE_ROLES=scanner PEEPHOLE_CLUSTER_NAME=scanner-2 PEEPHOLE_CLUSTER_LISTEN=0.0.0.0:7443 \
    PEEPHOLE_JOIN_TOKEN=peephole1:garbage \
    bash install.sh > /tmp/badjoin.log 2>&1 || { cat /tmp/badjoin.log; exit 1; }
grep -q 'joining the cluster failed' /tmp/badjoin.log
# Without a terminal no third-party API is used unless asked for.
if grep -q '\[internetdb\]' /etc/peephole/config.toml; then echo "unattended install enabled InternetDB"; exit 1; fi
echo "== unattended direct: the trap takes 80/443 itself, no proxy trusted, no nginx"
reset_install
# PEEPHOLE_TRUSTED_PROXIES stays preset (10.0.0.0/8): direct ignores it, with a warning.
env -u MAXMIND_ACCOUNT_ID -u MAXMIND_LICENSE_KEY -u PEEPHOLE_DOMAIN \
    PEEPHOLE_FRONT=direct PEEPHOLE_ROLES=listener,scanner PEEPHOLE_OWN_ADDRESSES=198.51.100.7 \
    bash install.sh > /tmp/direct.log 2>&1 || { cat /tmp/direct.log; exit 1; }
grep -Eq '^trap_listen = "(0\.0\.0\.0|\[::\]):80"' /etc/peephole/config.toml
grep -Eq '^trap_tls_listen = "(0\.0\.0\.0|\[::\]):443"' /etc/peephole/config.toml
grep -q '^trusted_proxies = \[\]' /etc/peephole/config.toml
if grep -q '10\.0\.0\.0/8' /etc/peephole/config.toml; then echo "direct config trusts 10.0.0.0/8"; exit 1; fi
grep -q 'PEEPHOLE_TRUSTED_PROXIES is ignored' /tmp/direct.log
# own_addresses inside the one [scan] table.
[ "$(grep -c '^\[scan\]' /etc/peephole/config.toml)" = 1 ]
grep -q '^own_addresses = \["198.51.100.7"\]' /etc/peephole/config.toml
[ "$(sed -n '/^\[/h; /^own_addresses/{x;p}' /etc/peephole/config.toml)" = "[scan]" ]
/usr/local/bin/peephole check-config /etc/peephole/config.toml
test ! -e /etc/peephole/nginx.example.conf
grep -q 'ports 80 and 443 itself.*Open 80/tcp, 443/tcp, 7443/tcp$' /tmp/direct.log
if grep -qi 'nginx\|trap listener (' /tmp/direct.log; then echo "direct install talks about nginx"; cat /tmp/direct.log; exit 1; fi

echo "== direct with the web role is refused before anything is written (nginx shares 443 by name instead)"
reset_install
if PEEPHOLE_FRONT=direct PEEPHOLE_ROLES=listener,web bash install.sh > /tmp/direct-web.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q 'admin site needs it too' /tmp/direct-web.log
test ! -e /usr/local/bin/peephole

echo "== wizard: direct with the web role is explained and asked again (default local)"
reset_install
# in front: direct (refused) · then the default · own addresses: none; the rest at its
# defaults (advertise: the admin domain, which points here)
printf 'direct\n\n\n' > /tmp/answers
env -u PEEPHOLE_CLUSTER_ADVERTISE PEEPHOLE_ROLES=listener,web PEEPHOLE_TTY=/tmp/answers bash install.sh > /tmp/direct-web-wizard.log 2>&1 \
    || { cat /tmp/direct-web-wizard.log; exit 1; }
grep -q '^advertise = "peephole.test:7443"' /etc/peephole/config.toml
grep -q 'admin site needs it too' /tmp/direct-web-wizard.log
grep -q '^trap_listen = "127.0.0.1:8080"' /etc/peephole/config.toml
test -f /etc/peephole/nginx-stream.example.conf

echo "== direct with port 80 taken is refused; without PEEPHOLE_FRONT the default becomes local"
reset_install
python3 -m http.server 80 --bind 0.0.0.0 >/dev/null 2>&1 &
busy_pid=$!
for _ in $(seq 1 50); do curl -fs -o /dev/null http://127.0.0.1:80/ && break; sleep 0.1; done
if env -u PEEPHOLE_TRUSTED_PROXIES PEEPHOLE_FRONT=direct PEEPHOLE_ROLES=listener \
    bash install.sh > /tmp/direct-busy.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q 'port 80.* in use' /tmp/direct-busy.log
test ! -e /etc/peephole/config.toml
env -u PEEPHOLE_TRUSTED_PROXIES PEEPHOLE_ROLES=listener \
    bash install.sh > /tmp/default-busy.log 2>&1 || { cat /tmp/default-busy.log; exit 1; }
grep -q '^trap_listen = "127.0.0.1:8080"' /etc/peephole/config.toml
kill "$busy_pid"; wait "$busy_pid" 2>/dev/null || true

echo "== unattended without anything in front preset, nothing on 80/443: direct"
reset_install
env -u PEEPHOLE_TRUSTED_PROXIES PEEPHOLE_ROLES=listener \
    bash install.sh > /tmp/default-direct.log 2>&1 || { cat /tmp/default-direct.log; exit 1; }
grep -Eq '^trap_listen = "(0\.0\.0\.0|\[::\]):80"' /etc/peephole/config.toml

echo "== remote needs the proxy's address: no default"
reset_install
if env -u PEEPHOLE_TRUSTED_PROXIES PEEPHOLE_FRONT=remote PEEPHOLE_ROLES=listener \
    bash install.sh > /tmp/remote-none.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q 'missing required setting: PEEPHOLE_TRUSTED_PROXIES' /tmp/remote-none.log
test ! -e /etc/peephole/config.toml
PEEPHOLE_FRONT=remote PEEPHOLE_ROLES=listener PEEPHOLE_TRUSTED_PROXIES=192.0.2.10,2001:db8::/64 \
    bash install.sh > /tmp/remote.log 2>&1 || { cat /tmp/remote.log; exit 1; }
grep -Eq '^trap_listen = "(0\.0\.0\.0|\[::\]):8080"' /etc/peephole/config.toml
grep -Eq '^trap_tls_listen = "(0\.0\.0\.0|\[::\]):8081"' /etc/peephole/config.toml
# A bare address is that one host.
grep -q '^trusted_proxies = \["192.0.2.10/32","2001:db8::/64"\]' /etc/peephole/config.toml
grep -q 'PROXY protocol v2' /tmp/remote.log
grep -q 'not health-check' /tmp/remote.log
# No web role: nothing for an nginx on this machine to do.
if grep -q 'rm /etc/nginx/sites-enabled/default' /tmp/remote.log; then echo "remote trap told to set up a local nginx"; exit 1; fi
/usr/local/bin/peephole check-config /etc/peephole/config.toml

echo "== a bad trusted proxy is refused before anything is written"
reset_install
if PEEPHOLE_FRONT=remote PEEPHOLE_ROLES=listener PEEPHOLE_TRUSTED_PROXIES=10.0.0.0/33 \
    bash install.sh > /tmp/remote-bad.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q "'10.0.0.0/33' is not an address or CIDR" /tmp/remote-bad.log
test ! -e /etc/peephole/config.toml
test ! -e /usr/local/bin/peephole

echo "== the admin domain is normalised"
reset_install
PEEPHOLE_FRONT=remote PEEPHOLE_DOMAIN='https://Peephole.Example.net/admin/' \
    bash install.sh > /tmp/domain.log 2>&1 || { cat /tmp/domain.log; exit 1; }
grep -q '^rp_id = "peephole.example.net"' /etc/peephole/config.toml
grep -q '^origin = "https://peephole.example.net"' /etc/peephole/config.toml
grep -q 'server_name peephole.example.net;' /etc/peephole/nginx.example.conf
reset_install
if PEEPHOLE_FRONT=remote PEEPHOLE_DOMAIN='not a domain' bash install.sh > /tmp/domain-bad.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q "not a host name" /tmp/domain-bad.log
test ! -e /etc/peephole/config.toml
test ! -e /usr/local/bin/peephole

echo "== a taken trap port: unattended stops, the wizard offers the next free ones"
reset_install
python3 -m http.server 8080 --bind 127.0.0.1 >/dev/null 2>&1 &
busy_pid=$!
for _ in $(seq 1 50); do curl -fs -o /dev/null http://127.0.0.1:8080/ && break; sleep 0.1; done
if PEEPHOLE_FRONT=local PEEPHOLE_ROLES=listener bash install.sh > /tmp/port-busy.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q 'port 8080 for the trap listener (127.0.0.1:8080) is in use' /tmp/port-busy.log
test ! -e /etc/peephole/config.toml
# in front: local · 127.0.0.1:8081 for the trap? yes · 127.0.0.1:8082 for TLS? yes ·
# own addresses: none · nginx? no · node name · advertise · token: none · MaxMind: skip ·
# API keys: skip · InternetDB? no
printf 'local\ny\ny\n\nn\ntrap-2\ntrap2.example:7443\n\n\n\n\nn\n' > /tmp/answers
env -u MAXMIND_ACCOUNT_ID -u MAXMIND_LICENSE_KEY -u PEEPHOLE_TRUSTED_PROXIES -u PEEPHOLE_CLUSTER_ADVERTISE \
    PEEPHOLE_ROLES=listener \
    PEEPHOLE_TTY=/tmp/answers bash install.sh > /tmp/port-offer.log 2>&1 || { cat /tmp/port-offer.log; exit 1; }
grep -q '^trap_listen = "127.0.0.1:8081"' /etc/peephole/config.toml
grep -q '^trap_tls_listen = "127.0.0.1:8082"' /etc/peephole/config.toml
grep -q 'proxy_pass http://127.0.0.1:8081;' /etc/peephole/nginx.example.conf
grep -q 'proxy_pass 127.0.0.1:8082;' /etc/peephole/nginx-stream.example.conf
grep -q '^node_name = "trap-2"' /etc/peephole/config.toml
grep -q '^advertise = "trap2.example:7443"' /etc/peephole/config.toml
kill "$busy_pid"; wait "$busy_pid" 2>/dev/null || true

echo "== advertise is required: unattended without one or a default stops before anything is written"
reset_install
# A proxy elsewhere: the admin domain need not point here, and no public address is known.
if env -u PEEPHOLE_CLUSTER_ADVERTISE PEEPHOLE_FRONT=remote bash install.sh > /tmp/advertise-none.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q 'missing required setting: PEEPHOLE_CLUSTER_ADVERTISE' /tmp/advertise-none.log
test ! -e /etc/peephole/config.toml
test ! -e /usr/local/bin/peephole
if PEEPHOLE_FRONT=remote PEEPHOLE_CLUSTER_ADVERTISE=bogus bash install.sh > /tmp/advertise-bad.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q "PEEPHOLE_CLUSTER_ADVERTISE: 'bogus' is not host:port" /tmp/advertise-bad.log
test ! -e /usr/local/bin/peephole
# The admin domain behind nginx here: its name is the default. PEEPHOLE_CLUSTER=0 is ignored.
env -u PEEPHOLE_CLUSTER_ADVERTISE PEEPHOLE_ROLES=listener,web PEEPHOLE_FRONT=local PEEPHOLE_CLUSTER=0 \
    bash install.sh > /tmp/advertise-default.log 2>&1 || { cat /tmp/advertise-default.log; exit 1; }
grep -q '^\[cluster\]' /etc/peephole/config.toml
grep -q '^advertise = "peephole.test:7443"' /etc/peephole/config.toml
grep -qxF "listen = \"${LISTEN_ANY}:7443\"" /etc/peephole/config.toml
grep -q 'other members dial peephole.test:7443' /tmp/advertise-default.log
echo "== ok"
