#!/usr/bin/env bash
# Exercises install.sh against a locally served tarball: fresh install,
# no-op re-run, forced upgrades (edited rules and unit kept, database backed
# up), a failed upgrade that rolls back, and the wizard.
# Runs as root in a throwaway Debian/Ubuntu container (CI: ubuntu:24.04).
# PEEPHOLE_BIN is the release binary (default target/release/peephole).
set -euo pipefail
cd "$(dirname "$0")/.."
case "$(uname -m)" in aarch64|arm64) TARGET=aarch64-unknown-linux-gnu ;; *) TARGET=x86_64-unknown-linux-gnu ;; esac
ASSET="peephole-${TARGET}"
apt-get update -qq && apt-get install -y -qq curl ca-certificates python3 systemd nmap sqlite3 procps nginx-light libnginx-mod-stream openssl >/dev/null

echo "== deploy files: nginx example generated by install.sh, nginx -t, systemd-analyze verify"
bash tests/deploy-check.sh

# The tarball, built like CI builds it; its version is what the binary
# reports, so a re-run sees the same version and does nothing.
BIN="${PEEPHOLE_BIN:-target/release/peephole}"
V1="$("$BIN" --version | awk '{print $2}')"
rm -rf "/tmp/$ASSET" /tmp/srv
tools/package.sh "$BIN" "$TARGET" "$V1" 0123456789abcdef0123456789abcdef01234567 /tmp/srv >/dev/null
tar -xzf "/tmp/srv/$ASSET.tar.gz" -C /tmp   # staged copy that later steps change and repack
repack() { ( cd /tmp && tar -czf "srv/$ASSET.tar.gz" "$ASSET" && cd srv && sha256sum "$ASSET.tar.gz" > "$ASSET.tar.gz.sha256" ); }
( cd /tmp/srv && python3 -m http.server 8999 >/dev/null 2>&1 & )
for _ in $(seq 1 50); do curl -fs -o /dev/null http://127.0.0.1:8999/ && break; sleep 0.1; done

# systemd is not PID 1 in a container: stub systemctl so the script's
# service steps become no-ops we can observe. /tmp/fail-start makes the next
# restart fail like a new version that does not come up, after "migrating"
# the database to a newer schema.
mkdir -p /tmp/bin
cat > /tmp/bin/systemctl <<'STUB'
#!/bin/sh
echo "systemctl $*" >> /tmp/systemctl.log
case "$1" in
  is-enabled) [ -e /tmp/enabled ]; exit $? ;;
  enable) touch /tmp/enabled ;;
  restart)
    if [ -e /tmp/fail-start ]; then
      rm -f /tmp/fail-start
      sqlite3 /var/lib/peephole/peephole.db 'PRAGMA user_version = 999'
      exit 1
    fi ;;
esac
exit 0
STUB
chmod +x /tmp/bin/systemctl
export PATH="/tmp/bin:$PATH"
export PEEPHOLE_SKIP_APT=1 PEEPHOLE_SKIP_HEALTH=1 BASE_URL="http://127.0.0.1:8999"
export MAXMIND_ACCOUNT_ID=1 MAXMIND_LICENSE_KEY=k PEEPHOLE_DOMAIN=peephole.test PEEPHOLE_TRUSTED_PROXIES=10.0.0.0/8

echo "== token extraction survives journalctl prefixes"
tok="$(printf 'Sep 30 10:00:00 host peephole[123]: Open /enroll on the admin interface and enter this one-time token:\nSep 30 10:00:00 host peephole[123]: \nSep 30 10:00:00 host peephole[123]:   3f2a1c4e-1111-4222-8333-444455556666\n' | bash install.sh --extract-token)"
[ "$tok" = "3f2a1c4e-1111-4222-8333-444455556666" ] || { echo "token extraction broken: '$tok'"; exit 1; }

echo "== refuses to install when systemd is not PID 1 (unless overridden)"
if PEEPHOLE_ALLOW_NO_SYSTEMD='' bash install.sh >/tmp/nopid1.log 2>&1; then echo "expected failure"; exit 1; fi
grep -q "PID 1" /tmp/nopid1.log
export PEEPHOLE_ALLOW_NO_SYSTEMD=1

echo "== a version that is not a release tag is refused"
if PEEPHOLE_VERSION=../evil bash install.sh >/tmp/badver.log 2>&1; then echo "expected failure"; exit 1; fi
grep -q "release tag" /tmp/badver.log

echo "== PEEPHOLE_VERIFY=1 without a verifiable attestation is refused before anything is installed"
# The local test release has no attestation; without gh it cannot be checked at all.
if command -v gh >/dev/null 2>&1; then expect="did not verify"; else expect="needs the GitHub CLI"; fi
if PEEPHOLE_VERIFY=1 bash install.sh >/tmp/verify.log 2>&1; then echo "expected failure"; exit 1; fi
grep -q "$expect" /tmp/verify.log
test ! -e /usr/local/bin/peephole

# The nginx steps in the closing summary appear in this order (certificate
# while the distribution's default site still serves, then the default site
# out of the way of the catch-all, then the site in, then a reload).
step_line() { grep -nF -- "$1" "$2" | head -1 | cut -d: -f1; }
steps_in_order() {
    local log="$1" prev=0 n; shift
    for s in "$@"; do
        n="$(step_line "$s" "$log")"
        if [ -z "$n" ] || [ "$n" -le "$prev" ]; then
            echo "nginx step '$s' missing or out of order"; cat "$log"; exit 1
        fi
        prev="$n"
    done
}

echo "== fresh install"
bash install.sh > /tmp/fresh.log 2>&1 || { cat /tmp/fresh.log; exit 1; }
test -x /usr/local/bin/peephole
test -f /etc/peephole/config.toml
test -f /etc/peephole/rules/sqli.toml
test -f /etc/peephole/nginx.example.conf
test -f /var/lib/peephole/.installed-rules.sha256
test -f /var/lib/peephole/.installed-unit.sha256
test -f /etc/peephole/config.example.toml
[ "$(stat -c %a /etc/peephole)" = 750 ] && [ "$(stat -c %a /var/lib/peephole)" = 700 ]
[ "$(stat -c %a /etc/peephole/config.toml)" = 600 ]
grep -q '^never_scan = \[\]' /etc/peephole/config.toml
grep -q 'commit 0123456789ab' /tmp/fresh.log
grep -q 'peephole.test' /etc/peephole/config.toml
grep -q 'server_name peephole.test;' /etc/peephole/nginx.example.conf
grep -q 'default_server' /etc/peephole/nginx.example.conf
grep -q 'systemctl enable --now peephole' /tmp/systemctl.log
steps_in_order /tmp/fresh.log 'certbot certonly --nginx -d peephole.test' 'rm /etc/nginx/sites-enabled/default' \
    'cp /etc/peephole/nginx.example.conf' 'ln -s ../sites-available/peephole' 'nginx -t && systemctl reload nginx'
grep -q 'listen 443 ssl http2;' /etc/peephole/nginx.example.conf
if grep -q '^ *http2 on' /etc/peephole/nginx.example.conf; then echo "http2 on needs nginx >= 1.25.1"; exit 1; fi
grep -q 'sites-enabled/default' /etc/peephole/nginx.example.conf
# No proxy on this machine: the trap's TLS listener faces the remote proxy,
# and nginx here keeps 443 for the admin site (no stream config).
grep -q '^trap_tls_listen = "0.0.0.0:8081"' /etc/peephole/config.toml
test ! -e /etc/peephole/nginx-stream.example.conf
grep -q 'ssl_reject_handshake on' /etc/peephole/nginx.example.conf

echo "== re-run is a no-op"
out="$(bash install.sh)"
echo "$out" | grep -q "already up to date"

echo "== forced upgrade keeps an edited rule and drops .new beside it; an unedited unit is replaced"
echo '# operator edit' >> /etc/peephole/rules/sqli.toml
printf 'test2 2026-01-02T00:00:00Z 1111111111111111111111111111111111111111\n' > "/tmp/$ASSET/VERSION"
echo '# upstream change' >> "/tmp/$ASSET/rules/xss.toml"
echo '# upstream change' >> "/tmp/$ASSET/rules/sqli.toml"
echo '# upstream unit change' >> "/tmp/$ASSET/deploy/peephole.service"
repack
echo '# operator note' >> /etc/peephole/nginx.example.conf
# A database to back up (the daemon never ran here).
sqlite3 /var/lib/peephole/peephole.db 'CREATE TABLE t (x); PRAGMA user_version = 5'
chmod 0644 /var/lib/peephole/peephole.db
PEEPHOLE_FORCE=1 bash install.sh
grep -q '# operator note' /etc/peephole/nginx.example.conf
grep -q '# operator edit' /etc/peephole/rules/sqli.toml
test -f /etc/peephole/rules/sqli.toml.new
grep -q '# upstream change' /etc/peephole/rules/xss.toml
test ! -e /etc/peephole/rules/xss.toml.new
grep -q '# upstream unit change' /etc/systemd/system/peephole.service
test ! -e /etc/systemd/system/peephole.service.new
grep -q 'systemctl restart peephole' /tmp/systemctl.log
test -x /usr/local/bin/peephole.prev
[ "$(stat -c %a /var/lib/peephole/peephole.db)" = 600 ]
backup="$(ls /var/lib/peephole/backup-*.db)"
[ "$(sqlite3 "$backup" 'PRAGMA user_version')" = 5 ]
[ "$(stat -c %a "$backup")" = 600 ]

echo "== an edited unit is kept and the new one placed beside it; two database backups are kept"
echo '# operator unit edit' >> /etc/systemd/system/peephole.service
echo '# upstream unit change 2' >> "/tmp/$ASSET/deploy/peephole.service"
repack
for _ in 1 2; do sleep 1.1; PEEPHOLE_FORCE=1 bash install.sh > /tmp/unit.log 2>&1 || { cat /tmp/unit.log; exit 1; }; done
grep -q '# operator unit edit' /etc/systemd/system/peephole.service
grep -q '# upstream unit change 2' /etc/systemd/system/peephole.service.new
grep -q 'systemctl edit peephole' /tmp/unit.log
[ "$(find /var/lib/peephole -name 'backup-*.db' | wc -l)" = 2 ]

echo "== a new version that does not start is rolled back: binary, rules, unit and database"
rm -f /etc/systemd/system/peephole.service.new
cp -p /etc/systemd/system/peephole.service /tmp/unit.before
cp -a /etc/peephole/rules /tmp/rules.before
echo '# broken release' >> "/tmp/$ASSET/rules/xss.toml"
echo '# broken release' >> "/tmp/$ASSET/deploy/peephole.service"
repack
touch /tmp/fail-start
if PEEPHOLE_FORCE=1 bash install.sh > /tmp/rollback.log 2>&1; then echo "expected failure"; cat /tmp/rollback.log; exit 1; fi
grep -q 'rolled back' /tmp/rollback.log
grep -q 'running again' /tmp/rollback.log
grep -q 'restoring /var/lib/peephole/backup-' /tmp/rollback.log
diff -r /tmp/rules.before /etc/peephole/rules
cmp /tmp/unit.before /etc/systemd/system/peephole.service
test ! -e /etc/systemd/system/peephole.service.new
test ! -e /usr/local/bin/peephole.prev
[ "$(sqlite3 /var/lib/peephole/peephole.db 'PRAGMA user_version')" = 5 ]
/usr/local/bin/peephole --version

echo "== forced re-run with wizard variables set leaves config and nginx example alone"
md5sum /etc/peephole/config.toml /etc/peephole/nginx.example.conf > /tmp/before.md5
PEEPHOLE_FORCE=1 PEEPHOLE_ROLES=scanner PEEPHOLE_LOCAL_PROXY=1 PEEPHOLE_CLUSTER=1 \
    PEEPHOLE_CLUSTER_NAME=other PEEPHOLE_CLUSTER_LISTEN=0.0.0.0:7443 PEEPHOLE_REMOTE_CONFIG=1 \
    bash install.sh > /tmp/forced-vars.log 2>&1 || { cat /tmp/forced-vars.log; exit 1; }
md5sum -c --quiet /tmp/before.md5

echo "== fresh headless scanner in distributed mode: no domain, no MaxMind"
rm -rf /etc/peephole /var/lib/peephole /usr/local/bin/peephole /usr/local/bin/peephole.prev /tmp/enabled
env -u MAXMIND_ACCOUNT_ID -u MAXMIND_LICENSE_KEY -u PEEPHOLE_DOMAIN \
    PEEPHOLE_ROLES=scanner PEEPHOLE_CLUSTER_NAME=scanner-1 PEEPHOLE_CLUSTER_LISTEN=0.0.0.0:7443 \
    bash install.sh > /tmp/headless.log 2>&1 || { cat /tmp/headless.log; exit 1; }
grep -q '^\[cluster\]' /etc/peephole/config.toml
grep -q '^listener = false' /etc/peephole/config.toml
grep -q '^web = false' /etc/peephole/config.toml
if grep -q 'webauthn\|maxmind\|trap_listen\|admin_listen' /etc/peephole/config.toml; then
    echo "headless config has role-specific settings"; exit 1
fi
grep -q 'ed25519:' /tmp/headless.log
test ! -e /etc/peephole/nginx.example.conf
/usr/local/bin/peephole check-config /etc/peephole/config.toml
# The node lists itself once the daemon has run (`cluster members` is read-only
# and systemd is stubbed here); the config names it.
grep -q '^node_name = "scanner-1"' /etc/peephole/config.toml
reset_install() {
    rm -rf /etc/peephole /var/lib/peephole /usr/local/bin/peephole /usr/local/bin/peephole.prev /tmp/enabled
}

echo "== wizard: trap only, behind a local nginx (answers typed at the prompts)"
reset_install
# trap? yes · scanner? no · web? no · local proxy? yes · cluster? no · MaxMind: skip ·
# AbuseIPDB key · Shodan: skip · GreyNoise: skip · InternetDB? no
printf 'y\nn\nn\ny\n\n\nabuse-key-1\n\n\nn\n' > /tmp/answers
# PEEPHOLE_TRUSTED_PROXIES stays preset (10.0.0.0/8): the local proxy answer replaces it, with a warning.
env -u MAXMIND_ACCOUNT_ID -u MAXMIND_LICENSE_KEY -u PEEPHOLE_DOMAIN \
    PEEPHOLE_TTY=/tmp/answers bash install.sh > /tmp/wizard1.log 2>&1 || { cat /tmp/wizard1.log; exit 1; }
grep -q 'PEEPHOLE_TRUSTED_PROXIES.*ignored' /tmp/wizard1.log
grep -q '^listener = true' /etc/peephole/config.toml
grep -q '^scanner = false' /etc/peephole/config.toml
grep -q '^web = false' /etc/peephole/config.toml
grep -q '^trap_listen = "127.0.0.1:8080"' /etc/peephole/config.toml
grep -q '^trusted_proxies = \["127.0.0.1/32","::1/128"\]' /etc/peephole/config.toml
if grep -q 'webauthn\|maxmind\|\[cluster\]\|admin_listen' /etc/peephole/config.toml; then
    echo "trap-only config has other roles' settings"; cat /etc/peephole/config.toml; exit 1
fi
grep -q '^api_key = "abuse-key-1"' /etc/peephole/config.toml
if grep -q '\[shodan\]\|\[greynoise\]\|\[internetdb\]' /etc/peephole/config.toml; then
    echo "skipped enrichment APIs were configured"; cat /etc/peephole/config.toml; exit 1
fi
/usr/local/bin/peephole check-config /etc/peephole/config.toml
grep -q 'trap listener (127.0.0.1:8080)' /tmp/wizard1.log
grep -q '^trap_tls_listen = "127.0.0.1:8081"' /etc/peephole/config.toml
steps_in_order /tmp/wizard1.log 'rm /etc/nginx/sites-enabled/default' 'cp /etc/peephole/nginx.example.conf' \
    'cp /etc/peephole/nginx-stream.example.conf /etc/nginx/peephole-stream.conf' \
    "echo 'include /etc/nginx/peephole-stream.conf;' >> /etc/nginx/nginx.conf" 'nginx -t && systemctl reload nginx'
# Port 443 untouched to the trap's TLS listener, with a PROXY header.
grep -q 'proxy_pass 127.0.0.1:8081;' /etc/peephole/nginx-stream.example.conf
grep -q 'proxy_protocol on;' /etc/peephole/nginx-stream.example.conf
if grep -q 'ssl_preread on' /etc/peephole/nginx-stream.example.conf; then
    echo "trap-only stream config routes by name although there is no admin site"; exit 1
fi
if grep -q 'certbot\|certificate' /tmp/wizard1.log; then echo "trap-only node told to get a certificate"; exit 1; fi
grep -q 'default_server' /etc/peephole/nginx.example.conf
grep -q 'proxy_pass http://127.0.0.1:8080' /etc/peephole/nginx.example.conf
# shellcheck disable=SC2016  # the dollar sign is literal nginx syntax
grep -qF 'X-Forwarded-For $remote_addr' /etc/peephole/nginx.example.conf
if grep -q 'server_name peephole\|8443\|proxy_add_x_forwarded_for' /etc/peephole/nginx.example.conf; then
    echo "trap-only nginx example has an admin block or a spoofable header"; exit 1
fi

echo "== wizard: no role at all is refused before anything is written"
reset_install
printf 'n\nn\nn\n' > /tmp/answers
if env -u MAXMIND_ACCOUNT_ID -u MAXMIND_LICENSE_KEY -u PEEPHOLE_DOMAIN \
    PEEPHOLE_TTY=/tmp/answers bash install.sh > /tmp/wizard2.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q "at least one" /tmp/wizard2.log
test ! -e /etc/peephole/config.toml
test ! -e /usr/local/bin/peephole

echo "== wizard: a quote in an answer is refused"
reset_install
# trap? no · scanner? no · web? yes · domain with a quote
printf 'n\nn\ny\nbad"domain\n' > /tmp/answers
if env -u MAXMIND_ACCOUNT_ID -u MAXMIND_LICENSE_KEY -u PEEPHOLE_DOMAIN \
    PEEPHOLE_TTY=/tmp/answers bash install.sh > /tmp/wizard3.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q "not allowed" /tmp/wizard3.log
test ! -e /etc/peephole/config.toml
test ! -e /usr/local/bin/peephole

echo "== preset roles with no role in them are refused before anything is written"
reset_install
if PEEPHOLE_ROLES=, bash install.sh > /tmp/noroles.log 2>&1; then echo "expected failure"; exit 1; fi
grep -q "at least one" /tmp/noroles.log
test ! -e /usr/local/bin/peephole

echo "== wizard: a value the binary rejects leaves no config behind"
reset_install
# trap? no · scanner? yes · web? no · cluster? yes · name · listen "bogus" ·
# advertise (none) · token (none) · remote config? no · MaxMind: skip
printf 'n\ny\nn\ny\nscanner-9\nbogus\n\n\nn\n\n' > /tmp/answers
if env -u MAXMIND_ACCOUNT_ID -u MAXMIND_LICENSE_KEY -u PEEPHOLE_DOMAIN \
    PEEPHOLE_TTY=/tmp/answers bash install.sh > /tmp/wizard-bad.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q "failed validation" /tmp/wizard-bad.log
test ! -e /etc/peephole/config.toml

echo "== wizard: re-run after the rejected answer asks again (scanner in a cluster, remote configuration on)"
# No reset: the binary and rules from the failed run are in place.
# trap? no · scanner? yes · web? no · cluster? yes · name · listen (default) ·
# advertise · token (none) · remote config? yes · MaxMind: skip
printf 'n\ny\nn\ny\nscanner-9\n\nscan9.example:7443\n\ny\n\n' > /tmp/answers
env -u MAXMIND_ACCOUNT_ID -u MAXMIND_LICENSE_KEY -u PEEPHOLE_DOMAIN \
    PEEPHOLE_TTY=/tmp/answers bash install.sh > /tmp/wizard4.log 2>&1 || { cat /tmp/wizard4.log; exit 1; }
if grep -q 'already up to date' /tmp/wizard4.log; then echo "re-run after a failed first install skipped the wizard"; exit 1; fi
grep -q '^node_name = "scanner-9"' /etc/peephole/config.toml
grep -q '^listen = "0.0.0.0:7443"' /etc/peephole/config.toml
grep -q '^advertise = "scan9.example:7443"' /etc/peephole/config.toml
grep -q '^remote_config = true' /etc/peephole/config.toml
# The InternetDB question was not answered: its default (yes) applies.
grep -q '^\[internetdb\]' /etc/peephole/config.toml
grep -q 'peephole-cfg1:' /tmp/wizard4.log
grep -q 'ed25519:' /tmp/wizard4.log
/usr/local/bin/peephole check-config /etc/peephole/config.toml | grep -q 'remote config: on'

# certbot stand-in: records its arguments and writes a self-signed
# certificate where Let's Encrypt would; /tmp/certbot-fail makes it fail.
cat > /tmp/bin/certbot <<'STUB'
#!/bin/sh
echo "certbot $*" >> /tmp/certbot.log
[ -e /tmp/certbot-fail ] && exit 1
d=""
while [ $# -gt 0 ]; do [ "$1" = -d ] && d="$2"; shift; done
mkdir -p "/etc/letsencrypt/live/$d"
openssl req -x509 -newkey rsa:2048 -nodes -days 1 -subj "/CN=$d" \
    -keyout "/etc/letsencrypt/live/$d/privkey.pem" -out "/etc/letsencrypt/live/$d/fullchain.pem" >/dev/null 2>&1
STUB
chmod +x /tmp/bin/certbot
reset_nginx() {
    rm -rf /etc/nginx/sites-available/peephole /etc/nginx/sites-enabled/peephole /etc/letsencrypt /tmp/certbot.log /tmp/certbot-fail \
        /etc/nginx/peephole-stream.conf
    sed -i '\|^# peephole: port 443 by server name|d; \|^include /etc/nginx/peephole-stream.conf;|d' /etc/nginx/nginx.conf
    [ -e /etc/nginx/sites-enabled/default ] || ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
}

echo "== PEEPHOLE_NGINX=1: certificate, default site out, site in, nginx -t, reload"
reset_install; reset_nginx
PEEPHOLE_NGINX=1 PEEPHOLE_LOCAL_PROXY=1 bash install.sh > /tmp/nginx-auto.log 2>&1 || { cat /tmp/nginx-auto.log; exit 1; }
grep -q -- '-d peephole.test' /tmp/certbot.log
grep -q -- '--register-unsafely-without-email' /tmp/certbot.log
grep -q -- '--deploy-hook systemctl reload nginx' /tmp/certbot.log
test -f /etc/nginx/sites-available/peephole
[ "$(readlink /etc/nginx/sites-enabled/peephole)" = ../sites-available/peephole ]
test ! -e /etc/nginx/sites-enabled/default
grep -q 'server_name peephole.test;' /etc/nginx/sites-available/peephole
# Port 443 by server name: the stream config is in, included once, and the
# admin site moved behind it.
grep -q 'ssl_preread on;' /etc/nginx/peephole-stream.conf
[ "$(grep -c '^include /etc/nginx/peephole-stream.conf;' /etc/nginx/nginx.conf)" = 1 ]
grep -q 'listen 127.0.0.1:8444 ssl http2 proxy_protocol;' /etc/nginx/sites-available/peephole
if [ ! -e /proc/net/if_inet6 ] && grep -q 'listen \[::\]' /etc/nginx/sites-available/peephole /etc/nginx/peephole-stream.conf; then
    echo "IPv6 listeners kept on a machine without IPv6"; exit 1
fi
nginx -t -q
grep -q 'systemctl reload nginx' /tmp/systemctl.log
grep -q 'nginx is configured' /tmp/nginx-auto.log
if grep -q 'certbot certonly\|rm /etc/nginx/sites-enabled/default\|Terminate TLS' /tmp/nginx-auto.log; then
    echo "manual nginx steps printed although nginx was configured"; cat /tmp/nginx-auto.log; exit 1
fi

echo "== PEEPHOLE_NGINX=1, certificate refused: nginx left as it was, manual steps printed"
reset_install; reset_nginx
touch /tmp/certbot-fail
PEEPHOLE_NGINX=1 PEEPHOLE_LOCAL_PROXY=1 PEEPHOLE_ACME_EMAIL=ops@peephole.test \
    bash install.sh > /tmp/nginx-fail.log 2>&1 || { cat /tmp/nginx-fail.log; exit 1; }
grep -q -- '-m ops@peephole.test' /tmp/certbot.log
grep -q 'no certificate for peephole.test' /tmp/nginx-fail.log
test ! -e /etc/nginx/sites-available/peephole
test ! -e /etc/nginx/peephole-stream.conf
if grep -q 'peephole-stream' /etc/nginx/nginx.conf; then echo "include left behind"; exit 1; fi
test -L /etc/nginx/sites-enabled/default
steps_in_order /tmp/nginx-fail.log 'certbot certonly --nginx -d peephole.test' 'rm /etc/nginx/sites-enabled/default' \
    'cp /etc/peephole/nginx.example.conf' 'nginx -t && systemctl reload nginx'

echo "== PEEPHOLE_NGINX=1 for a trap that trusts a remote proxy is refused before anything is written"
reset_install; reset_nginx
if PEEPHOLE_NGINX=1 PEEPHOLE_LOCAL_PROXY=0 PEEPHOLE_ROLES=listener bash install.sh > /tmp/nginx-refused.log 2>&1; then
    echo "expected failure"; exit 1
fi
grep -q 'PEEPHOLE_NGINX=1 needs' /tmp/nginx-refused.log
test ! -e /usr/local/bin/peephole
reset_nginx

echo "== unattended: a bad join token does not fail the install"
reset_install
env -u MAXMIND_ACCOUNT_ID -u MAXMIND_LICENSE_KEY -u PEEPHOLE_DOMAIN \
    PEEPHOLE_ROLES=scanner PEEPHOLE_CLUSTER_NAME=scanner-2 PEEPHOLE_CLUSTER_LISTEN=0.0.0.0:7443 \
    PEEPHOLE_JOIN_TOKEN=peephole1:garbage PEEPHOLE_REMOTE_CONFIG=0 \
    bash install.sh > /tmp/badjoin.log 2>&1 || { cat /tmp/badjoin.log; exit 1; }
grep -q 'joining the cluster failed' /tmp/badjoin.log
grep -q '^remote_config = false' /etc/peephole/config.toml
# Without a terminal no third-party API is used unless asked for.
if grep -q '\[internetdb\]' /etc/peephole/config.toml; then echo "unattended install enabled InternetDB"; exit 1; fi
if grep -q 'peephole-cfg1:' /tmp/badjoin.log; then echo "locked node printed a config key"; exit 1; fi
echo "== ok"
